### ISSUE TITLE
`NimBLEClient::getService(ServiceUUID)` does not succeed with 16-bit ServiceUUID

### ISSUE THREAD

**Issue by wakwak-koba** [h2zero/NimBLE-Arduino#111]
The BLE-HID device I'm using in my test appears to own 0x1812 when I view the ServiceUUID list after doing `getSerices(true)`.
However, if I do not do `getServices(true)` first and do `getService(NimBLEUUID((uint16_t)0x1812)` it fails.

Successful Code:
```c++
NimBLEUUID    uuid_service((uint16_t)0x1812);

pClient->getServices(true);
auto pService = pClient->getService(uuid_service);
```
Failing code:
```c++
NimBLEUUID    uuid_service((uint16_t)0x1812);

// pClient->getServices(true);
auto pService = pClient->getService(uuid_service);   // nullptr is returned
```
The ServiceUUID on this device I needed was appearing as 00001812-0000-1000-8000-00805f9b34fb instead of 0x1812 in previous BLE libraries.
However, specifying 0001812-0000-1000-8000-00805f9b34fb still fails.

Failing code, too:
```c++
NimBLEUUID    uuid_service("0001812-0000-1000-8000-00805f9b34fb");

// pClient->getServices(true);
auto pService = pClient->getService(uuid_service);   // nullptr is returned

pClient->getServices(true);
pService = pClient->getService(uuid_service);   // nullptr is returned, too
```
What do you think ?
If it's a problem on the `ble_gattc_disc_svc_by_uuid()` side, solving it can be tricky...

**Comment by h2zero** [comment]
This is quite puzzling, it's possible there is a bug in the ble_gattc_disc_svc_by_uuid() but I would suspect not since no other issues regarding this have been reported and would likely have been by now on the upstream. 

My best guess is that the device you're connecting to does not respond to that request and only seems to respond to the "get all" request.

If you post a log with NimBLE debug enabled in nimconfig.h I could confirm/deny this.

**Comment by ntwallace** [comment]
I'm wondering if this is related to a bug I'm having where calling `createService(UUID)` or `createCharacteristic(UUID)` with a uint16_t UUID causes an abort boot loop on the ESP.

For example, `NimBLEService *serviceDevice = server->createService((uint16_t)0x180a);` results in: 
```Backtrace: 0x400943fc:0x3ffda530 0x4009462d:0x3ffda550 0x400fc043:0x3ffda570 0x400faace:0x3ffda5c0 0x400d42d1:0x3ffda5f0 0x400f261f:0x3ffda630 0x400907f5:0x3ffda660
  #0  0x400943fc:0x3ffda530 in invoke_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:707
  #1  0x4009462d:0x3ffda550 in abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:707
  #2  0x400fc043:0x3ffda570 in NimBLEServer::start() at lib/NimBLE/src/NimBLEServer.cpp:224
  #3  0x400faace:0x3ffda5c0 in NimBLEAdvertising::start() at lib/NimBLE/src/NimBLEAdvertising.cpp:149
  #4  0x400f261f:0x3ffda630 in TaskDraw(void*) at src/./tasks/TaskSerial.h:47
  #5  0x400907f5:0x3ffda660 in vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)```
```


But, `NimBLEService *serviceDevice = server->createService("7537fbd5-d66c-4b03-b132-47b1e18285ee");` works fine.

**Comment by h2zero** [comment]
I wonder about this, both of your issues involve uuid's in the 0x18xx range. I'll try to find what the issue could be and report back.

**Comment by h2zero** [comment]
Just did some testing using with a server with service uuid 0x1812 and client calling getService((uint16_t)0x1812) I have not encountered any issues.

I will need more information / code to reproduce.

**Comment by tonton81** [comment]
You need to call it like this:

NimBLEUUID    uuid_service(**(BLEUUID)**(uint16_t)0x1812);

Thats how mine connects using 16bit UUID on both NimBLE and BLEClient

**Comment by h2zero** [comment]
>NimBLEUUID uuid_service((BLEUUID)(uint16_t)0x1812); // <-- you need to cast it to BLEUUID

That's due to different internal data structures. In bluedroid it uses `esp_bt_uuid_t` and it's first member variable is `uint16_t`. This is not the case in NimBLE. It's also not necessary to do at all, just passing `(uint16_t)0x1812` or if preferred `NimBLEUUID((uint16_t)0x1812)` will do the job.

**Comment by tonton81** [comment]
I tried that as well. my UUID is 0xFFD0 for service which it won't accept, and 0xFFD1 is characteristic, which never reaches that point due to service failing

**Comment by h2zero** [comment]
This is strange behavior indeed, I have never seen this personally but that doesn't mean there isn't something wrong. What devices are you connecting to?

Also, the fix for this was posted above, before getting the specific service try calling `XBT_client[controller]->getServices(true);` and let me know if that works.

**Comment by tonton81** [comment]
It's a Morimoto XBT RGBW led controller

Yeah forgot to mention I added getServices(true), same issue

`void sync_XBT_controllers(int controller) {
  XBT_client[controller]->getServices(true);
  NimBLERemoteService* _service = XBT_client[controller]->getService((BLEUUID)((uint16_t)0xFFD0));
  if (_service == nullptr) {
    Serial.println("SERVICE ERROR");
    XBT_client[controller]->disconnect();
    return;
  }
`

**Comment by h2zero** [comment]
If that is the code you're using currently, please try changing:
```
getService((BLEUUID)((uint16_t)0xFFD0));
```
to: `getService(BLEUUID((uint16_t)0xFFD0));` or `getService("FFD0");` and let me know if it helps.

**Comment by tonton81** [comment]
Still service error on both attempts

`Connected to f0:b5:d1:8f:ba:e5
D NimBLEClient: "<< connect()"
D NimBLEClient: ">> deleteServices"
D NimBLEClient: "<< deleteServices"
D NimBLEClient: ">> retrieveServices"
D NimBLEClient: "Service Discovered >> status: 0 handle: 1"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService()"
D NimBLEClient: "Service Discovered >> status: 0 handle: 12"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService()"
D NimBLEClient: "Service Discovered >> status: 0 handle: 16"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService()"
D NimBLEClient: "Service Discovered >> status: 0 handle: 35"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService()"
D NimBLEClient: "Service Discovered >> status: 0 handle: 43"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService()"
D NimBLEClient: "Service Discovered >> status: 14 handle: -1"
D NimBLEClient: "<< << Service Discovered"
D NimBLEClient: "<< retrieveServices"
I NimBLEClient: "Found 5 services"
D NimBLEClient: ">> getService: uuid: 0xffd0"
D NimBLEClient: ">> retrieveServices"
D NimBLEClient: "Service Discovered >> status: 14 handle: -1"
D NimBLEClient: "<< << Service Discovered"
D NimBLEClient: "<< retrieveServices"
D NimBLEClient: "<< getService: not found"
SERVICE ERROR
D NimBLEClient: ">> connect(f0:b5:d1:8f:b6:b8)"
D NimBLEScan: ">> stop()"
D NimBLEScan: "<< stop()"
D NimBLEClient: "Got Client event "
D NimBLEClient: "Connection established"
D NimBLEClient: "Got Client event "
I NimBLEClient: "mtu update event; conn_handle=1 mtu=23"
D NimBLEClient: ">> deleteServices"
D NimBLEClient: "<< deleteServices"
Connected to f0:b5:d1:8f:b6:b8
D NimBLEClient: "<< connect()"
D NimBLEClient: ">> deleteServices"
D NimBLEClient: "<< deleteServices"
D NimBLEClient: ">> retrieveServices"
D NimBLEClient: "Service Discovered >> status: 0 handle: 1"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService()"
D NimBLEClient: "Service Discovered >> status: 0 handle: 12"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService()"
D NimBLEClient: "Service Discovered >> status: 0 handle: 16"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService()"
D NimBLEClient: "Service Discovered >> status: 0 handle: 35"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService()"
D NimBLEClient: "Service Discovered >> status: 0 handle: 43"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService()"
D NimBLEClient: "Service Discovered >> status: 14 handle: -1"
D NimBLEClient: "<< retrieveServices"
D NimBLEClient: "<< << Service Discovered"
I NimBLEClient: "Found 5 services"
D NimBLEClient: ">> getService: uuid: 0xffd0"
D NimBLEClient: ">> retrieveServices"
D NimBLEClient: "Service Discovered >> status: 14 handle: -1"
D NimBLEClient: "<< << Service Discovered"
D NimBLEClient: "<< retrieveServices"
D NimBLEClient: "<< getService: not found"
SERVICE ERROR
D NimBLEScan: ">> start(duration=1)"
D NimBLEScan: "<< start()"
Free Heap: 255704, debug refresh time: 2086`

**Comment by h2zero** [comment]
Thanks for the log, I should change those debug messages to print uuids.

If you connect with your phone how many services does it find? I can see there are 5, I'm wondering if there is some missing in the results.

**Comment by tonton81** [comment]
![Screenshot_20201227-184816_nRF Connect](https://user-images.githubusercontent.com/16903052/103181919-8cc41900-4874-11eb-8c2b-1d7ff34a413f.jpg)

**Comment by tonton81** [comment]
FFD0 is service and FFD1 is characteristic. These RGB modules don't seem to have authentication, their phone-app only links by highest RSSI value when phone is placed near the device. I don't need a close range as I connect to their pre-set mac address when it's found in the scan, making this universal accross all their units as they use static service and characteristic which is identical on all their units

**Comment by h2zero** [comment]
Awesome, thanks! So, seeing that there is only 5 services on the phone and the debug traces also showed 5 services, that would imply that there is something wrong with the uuid matching. I'm not sure why that would be but I'll start investigating.

**Comment by h2zero** [comment]
Just a thought, there might be an endian issue here. Could you try `getService` with the uuid `0xD0FF`? I don't know why or how that would be a problem but I would like to rule it out first.

**Comment by h2zero** [comment]
If you wouldn't mind, could you change [this line](https://github.com/h2zero/NimBLE-Arduino/blob/5cb454bfce3bf753e26d00817b7bf66cc0de447a/src/NimBLERemoteService.cpp#L52) to:
`NIMBLE_LOGD(LOG_TAG, "<< NimBLERemoteService: %s", m_uuid.toString().c_str());`
and post a log of the results. That will greatly speed up the troubleshooting.

**Comment by tonton81** [comment]
edited the line, tried with reversing endianess, still fail:

`Connected to f0:b5:d1:8f:b6:b8
D NimBLEClient: "<< connect()"
D NimBLEClient: ">> deleteServices"
D NimBLEClient: "<< deleteServices"
D NimBLEClient: ">> retrieveServices"
D NimBLEClient: "Service Discovered >> status: 0 handle: 1"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService: 0x1800"
D NimBLEClient: "Service Discovered >> status: 0 handle: 12"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService: 0x1801"
D NimBLEClient: "Service Discovered >> status: 0 handle: 16"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService: 0x180a"
D NimBLEClient: "Service Discovered >> status: 0 handle: 35"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService: 0000ffd0-0000-1000-8000-00805f9b34fb"
D NimBLEClient: "Service Discovered >> status: 0 handle: 43"
D NimBLERemoteService: ">> NimBLERemoteService()"
D NimBLERemoteService: "<< NimBLERemoteService: f000ffc0-0451-4000-b000-000000000000"
D NimBLEClient: "Service Discovered >> status: 14 handle: -1"
D NimBLEClient: "<< retrieveServices"
D NimBLEClient: "<< << Service Discovered"
I NimBLEClient: "Found 5 services"
D NimBLEClient: ">> getService: uuid: 0xffd0"
D NimBLEClient: ">> retrieveServices"
D NimBLEClient: "Service Discovered >> status: 14 handle: -1"
D NimBLEClient: "<< << Service Discovered"
D NimBLEClient: "<< retrieveServices"
D NimBLEClient: "<< getService: not found"
SERVICE ERROR
Free Heap: 254464, debug refresh time: 2001
XBT 0: connected
XBT 1: disconnected
XBT 2: connected
XBT 3: disconnected
D NimBLEScan: ">> start(duration=1)"
D NimBLEScan: "<< start()"
I NimBLEScan: "NEW DEVICE FOUND: 58:8a:3b:16:f3:18"
D NimBLEAdvertisedDevice: "payload: 02011a020a0c0bff4c001006081eb0727131"
I NimBLEScan: "NEW DEVICE FOUND: 7c:20:5f:14:71:3f"
D NimBLEAdvertisedDevice: "payload: 02011a020a0c0aff4c0010055e1c0220e5"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 7c:20:5f:14:71:3f"
I NimBLEScan: "NEW DEVICE FOUND: 00:f0:1c:63:09:c4"
D NimBLEAdvertisedDevice: "payload: 1eff0600010920021eac695509d4fde0d399fab31b9821690ea0daa9933f20"
I NimBLEScan: "NEW DEVICE FOUND: 42:1c:9a:1d:1f:55"
D NimBLEAdvertisedDevice: "payload: 03036ffd17166ffdd57f2f55c1df324f4bc63003a25913ac4a444570"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 42:1c:9a:1d:1f:55"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 42:1c:9a:1d:1f:55"
D NimBLEAdvertisedDevice: "payload: 03036ffd17166ffdd57f2f55c1df324f4bc63003a25913ac4a444570"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 42:1c:9a:1d:1f:55"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 7c:20:5f:14:71:3f"
D NimBLEAdvertisedDevice: "payload: 02011a020a0c0aff4c0010055e1c0220e5"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 7c:20:5f:14:71:3f"
D NimBLEScan: "discovery complete; reason=0"
D NimBLEScan: ">> start(duration=1)"
D NimBLEScan: "<< start()"
I NimBLEScan: "NEW DEVICE FOUND: 5d:fa:47:e2:5f:4c"
D NimBLEAdvertisedDevice: "payload: 0201021107fc9dd0b3cb84e0840642f3f7e1e0bfcb"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 5d:fa:47:e2:5f:4c"
I NimBLEScan: "NEW DEVICE FOUND: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 02010213ffffff30653362353832303264656134356362020af103035634"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 0709534849454c44"
I NimBLEScan: "NEW DEVICE FOUND: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401206f18070002010000000000000000000000000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
I NimBLEScan: "NEW DEVICE FOUND: 7c:20:5f:14:71:3f"
D NimBLEAdvertisedDevice: "payload: 02011a020a0c0aff4c0010055e1c0220e5"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 7c:20:5f:14:71:3f"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401016fcc6ea4eeb1d1ce6ea4eeb1d0065544b6000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
Free Heap: 254940, debug refresh time: 2001
XBT 0: connected
XBT 1: disconnected
XBT 2: connected
XBT 3: disconnected
D NimBLEScan: ">> start(duration=1)"
E NimBLEScan: "Scan already in progress"
D NimBLEScan: "discovery complete; reason=0"
D NimBLEScan: ">> start(duration=1)"
D NimBLEScan: "<< start()"
I NimBLEScan: "NEW DEVICE FOUND: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 02010213ffffff30653362353832303264656134356362020af103035634"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 0709534849454c44"
I NimBLEScan: "NEW DEVICE FOUND: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401016fcc6ea4eeb1d1ce6ea4eeb1d0065544b6000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
I NimBLEScan: "NEW DEVICE FOUND: 42:1c:9a:1d:1f:55"
D NimBLEAdvertisedDevice: "payload: 03036ffd17166ffdd57f2f55c1df324f4bc63003a25913ac4a444570"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 42:1c:9a:1d:1f:55"
I NimBLEScan: "NEW DEVICE FOUND: 00:f0:1c:63:09:c4"
D NimBLEAdvertisedDevice: "payload: 1eff0600010920021eac695509d4fde0d399fab31b9821690ea0daa9933f20"
I NimBLEScan: "NEW DEVICE FOUND: 7c:20:5f:14:71:3f"
D NimBLEAdvertisedDevice: "payload: 02011a020a0c0aff4c0010055e1c0220e5"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 7c:20:5f:14:71:3f"
Free Heap: 254648, debug refresh time: 2001
XBT 0: connected
XBT 1: disconnected
XBT 2: connected
XBT 3: disconnected
D NimBLEScan: ">> start(duration=1)"
E NimBLEScan: "Scan already in progress"
D NimBLEScan: "discovery complete; reason=0"
D NimBLEScan: ">> start(duration=1)"
D NimBLEScan: "<< start()"
I NimBLEScan: "NEW DEVICE FOUND: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401016fcc6ea4eeb1d1ce6ea4eeb1d0065544b6000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
I NimBLEScan: "NEW DEVICE FOUND: 42:1c:9a:1d:1f:55"
D NimBLEAdvertisedDevice: "payload: 03036ffd17166ffdd57f2f55c1df324f4bc63003a25913ac4a444570"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 42:1c:9a:1d:1f:55"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401016fcc6ea4eeb1d1ce6ea4eeb1d0065544b6000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
I NimBLEScan: "NEW DEVICE FOUND: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 02010213ffffff30653362353832303264656134356362020af103035634"
I NimBLEScan: "NEW DEVICE FOUND: 7c:20:5f:14:71:3f"
D NimBLEAdvertisedDevice: "payload: 02011a020a0c0aff4c0010055e1c0220e5"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 7c:20:5f:14:71:3f"
Free Heap: 254840, debug refresh time: 2001
XBT 0: connected
XBT 1: disconnected
XBT 2: connected
XBT 3: disconnected
D NimBLEScan: ">> start(duration=1)"
E NimBLEScan: "Scan already in progress"
D NimBLEScan: "discovery complete; reason=0"
D NimBLEScan: ">> start(duration=1)"
D NimBLEScan: "<< start()"
I NimBLEScan: "NEW DEVICE FOUND: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 02010213ffffff30653362353832303264656134356362020af103035634"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 0709534849454c44"
I NimBLEScan: "NEW DEVICE FOUND: 42:1c:9a:1d:1f:55"
D NimBLEAdvertisedDevice: "payload: 03036ffd17166ffdd57f2f55c1df324f4bc63003a25913ac4a444570"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 42:1c:9a:1d:1f:55"
I NimBLEScan: "NEW DEVICE FOUND: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401206f18070002010000000000000000000000000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401016fcc6ea4eeb1d1ce6ea4eeb1d0065544b6000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
Free Heap: 254964, debug refresh time: 2001
XBT 0: connected
XBT 1: disconnected
XBT 2: connected
XBT 3: disconnected
D NimBLEScan: ">> start(duration=1)"
E NimBLEScan: "Scan already in progress"
D NimBLEScan: "discovery complete; reason=0"
D NimBLEScan: ">> start(duration=1)"
D NimBLEScan: "<< start()"
I NimBLEScan: "NEW DEVICE FOUND: 7c:20:5f:14:71:3f"
D NimBLEAdvertisedDevice: "payload: 02011a020a0c0aff4c0010055e1c0220e5"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 7c:20:5f:14:71:3f"
I NimBLEScan: "NEW DEVICE FOUND: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 02010213ffffff30653362353832303264656134356362020af103035634"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 0709534849454c44"
I NimBLEScan: "NEW DEVICE FOUND: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401206f18070002010000000000000000000000000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
I NimBLEScan: "NEW DEVICE FOUND: 42:1c:9a:1d:1f:55"
D NimBLEAdvertisedDevice: "payload: 03036ffd17166ffdd57f2f55c1df324f4bc63003a25913ac4a444570"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 42:1c:9a:1d:1f:55"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401016fcc6ea4eeb1d1ce6ea4eeb1d0065544b6000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
I NimBLEScan: "NEW DEVICE FOUND: 00:f0:1c:63:09:c4"
D NimBLEAdvertisedDevice: "payload: 1eff0600010920021eac695509d4fde0d399fab31b9821690ea0daa9933f20"
I NimBLEScan: "NEW DEVICE FOUND: 58:8a:3b:16:f3:18"
D NimBLEAdvertisedDevice: "payload: 02011a020a0c0bff4c001006081eb0727131"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 58:8a:3b:16:f3:18"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 7c:20:5f:14:71:3f"
D NimBLEAdvertisedDevice: "payload: 02011a020a0c0aff4c0010055e1c0220e5"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 02010213ffffff30653362353832303264656134356362020af103035634"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 0709534849454c44"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401206f18070002010000000000000000000000000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 42:1c:9a:1d:1f:55"
D NimBLEAdvertisedDevice: "payload: 03036ffd17166ffdd57f2f55c1df324f4bc63003a25913ac4a444570"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 42:1c:9a:1d:1f:55"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 02011a1bff7500420401016fcc6ea4eeb1d1ce6ea4eeb1d0065544b6000000"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: cc:6e:a4:ee:b1:d1"
D NimBLEAdvertisedDevice: "payload: 1c085b54565d2053616d73756e67205136205365726965732028383229"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 02010213ffffff30653362353832303264656134356362020af103035634"
I NimBLEScan: "UPDATING PREVIOUSLY FOUND DEVICE: 6b:0e:cb:a8:95:1d"
D NimBLEAdvertisedDevice: "payload: 0709534849454c44"
Free Heap: 254520, debug refresh time: 2001
XBT 0: connected
XBT 1: disconnected
XBT 2: connected
XBT 3: disconnected`

**Comment by tonton81** [comment]
Easier to see with a snapshot i guess :P

![image](https://user-images.githubusercontent.com/16903052/103187732-a163d980-4893-11eb-881a-7998d175a58d.png)

**Comment by tonton81** [comment]
Looks like the 128 bit one went in!

`0000ffd0-0000-1000-8000-00805f9b34fb`

now it's asking for the char... So i guess 16bit is broken

**Comment by wakwak-koba** [comment]
I was the first person to publish this issue.

When `pClient-> getServices (true);` was not called in advance, finally, `ble_gattc_disc_svc_uuid_tx`   is called.
https://github.com/h2zero/NimBLE-Arduino/blob/5cb454bfce3bf753e26d00817b7bf66cc0de447a/src/nimble/host/src/ble_gattc.c#L1609-L1613

Here, since it is limited to `BLE_ATT_UUID_PRIMARY_SERVICE`, I guessed that `BLE_ATT_UUID_SECONDARY_SERVICE` might have been omitted from the search target, and I thought that this was unavoidable behavior, but I gave up, but my guess.

Is it a difference?

**Comment by tonton81** [comment]
wakwak i tried your copy but the ringbuffer compile error didnt let me run it last night. so far i know service and characteristic work at 128bits now, because i was able to control the LED channels, just gotta change my writeValue arrays to prevent compile warnings, but so far so good

**Comment by h2zero** [comment]
Lol, well that's interesting for sure. I'm not quite sure as to the best course of action yet but thank you all very much for helping out and posting data/solutions.

@tonton81 For now, using the 128 bit uuid's is the best way forward. NimBLE is very precise and does not filter off the default 128 bit uuid construction for uuid's during comparison, but this is something I can add to the library. For added simplicity you could call the getX() functions with `getX(BLEUUID((uint16_t)0xFFD0).to128());` for now. You can expect a proper fix for this soon.

@wakwak-koba 
>Here, since it is limited to BLE_ATT_UUID_PRIMARY_SERVICE, I guessed that BLE_ATT_UUID_SECONDARY_SERVICE might have been omitted from the search target

This is a very good thought, I will look at this more as well, not sure if it's related to your issue but it's worth investigaing. I will make a peripheral device with secondary services and test the effects.

**Comment by h2zero** [comment]
I went over this thread again and realized I didn't respond to @ntwallace, sorry about that.

> a bug I'm having where calling createService(UUID) or createCharacteristic(UUID) with a uint16_t UUID causes an abort boot loop on the ESP

I'm sure you fixed this by now, but just in case others come accross this, the error is caused by not calling `start()` on the service before advertising start.

**Comment by h2zero** [comment]
A note to add to this; The reason the original library worked in this scenario is due to it's use of `toString()` to convert the 16bit uuid to 128 and then perform a string comparison. I never noticed it before, but was a good idea for using it's code base. I'm working on something similar.

**Comment by tonton81** [comment]
Waaaay better than BLEClient at fast responses to disconnects and able to reconnect consistantly (so far) and without lockups. I'm pushing the color switching at 100ms but it can definately go faster, just cleaning up the code bloat first :)
(This is without the FreeRTOS.cpp mod people do for the timeout lockup on BLEClient (which doesn't effectively work after several disconnects!)).

https://www.youtube.com/watch?v=p4Ms35I--jI&feature=youtu.be

**Comment by h2zero** [comment]
Haha, glad you got it working 😄 . Looks very responsive in the video. You can push that to 7.5ms I'm sure.

Almost finished with the uuid issue, will finish testing tomorrow and push the fix. Thanks for the help!

**Comment by h2zero** [comment]
Fix has been pushed in commit 9327517.

**Comment by tonton81** [comment]
Ok, went to test both :)

`  NimBLERemoteService* _service = XBT_client[controller]->getService("0000ffd0-0000-1000-8000-00805f9b34fb");
  NimBLERemoteService* _service = XBT_client[controller]->getService((uint16_t)0xFFD0);
`

Both work

**Comment by h2zero** [comment]
Great, thanks for confirming!

**Comment by h2zero** [comment]
>By the way, for not loosing frames in BT on my device, I monitored the writeValue returns, it would toggle true or false on writes if i go below 2ms rates of writes, so I just delay(2) or delay(3) and all are successful now. Guess it's good way to monitor bandwidth thresholds :)

Yes, that would be a good way to flow control test.

**Comment by tonton81** [comment]
Service is fixed, char is failing now

Serial shows "CHAR FAIL!!" before a panic

`  XBT_characteristic[controller] = _service->getCharacteristic((uint16_t)0xFFD1); /* "0000ffd1-0000-1000-8000-00805f9b34fb" */
  if (XBT_characteristic[controller] == nullptr) {
    Serial.println("CHAR FAIL!!");
    XBT_client[controller]->disconnect();
    return;
  }`

**Comment by h2zero** [comment]
Yes, this is due to communicating to the NimBLE stack to ask for a 16bit uuid and it does exactly that. Since that code doesn't use the comparison check in the library it will still fail. Further changes will be necessary.

Can you decode the backtrace and post it?

**Comment by tonton81** [comment]
Debug option? I am new to ESP32 due to the fact I took the first thing that I got working on the XBT controller lol

**Comment by h2zero** [comment]
You will need [this](https://github.com/me-no-dev/EspExceptionDecoder), very important tool for esp32.

**Comment by tonton81** [comment]
![image](https://user-images.githubusercontent.com/16903052/103239548-d1ef5600-491b-11eb-9799-51e9996b853e.png)

**Comment by h2zero** [comment]
Ahh, there it is. Seems you have called writeValue somewhere after the getcharacteristic failed, which would make it a nullptr.

**Comment by h2zero** [comment]
I will work on the next part of the fix right away. I will update here when it's done.

**Comment by tonton81** [comment]
writeValue is protected by pClient's isConnected() in my sketch, that probably exaplains why the flag is 1 for isConnected before the services/characteristics is populated. If thats the case I would need to check nullptr on service and characteristic and isConnected() before doing writeValues, complex but that probably ressolves most issues with others who use BLE in general.

**Comment by h2zero** [comment]
>The disconnect() though should have dropped isConnected() to false when setting a bad characteristic

This can take some time to trigger, not reliable unless you wait for it. Checking if something is nullptr before calling it's methods is best practice for sure.

Here is a patch I made to address the rest of the uuid issue, if you wouldn't mind testing it before I push?
[uuid_patch.txt](https://github.com/h2zero/NimBLE-Arduino/files/5748662/uuid_patch.txt)

**Comment by tonton81** [comment]
I tried copy pasting it but failed miserably (the way i did it perhaps), has to remove some (-/+) and there was missing brackets. It's not working most likely i did something wrong here :P

**Comment by h2zero** [comment]
I messed up the patch command there, lol sorry about that. I push it to a branch to make it easier.

**Comment by tonton81** [comment]
Still get char faild

**Comment by tonton81** [comment]
This is the Debug output:
![image](https://user-images.githubusercontent.com/16903052/103242242-8c368b80-4923-11eb-961c-67f5a3adcd30.png)

**Comment by h2zero** [comment]
Can you post the debug of when you call getcharacteristic? All I see in there is the advertising results.

**Comment by tonton81** [comment]
![image](https://user-images.githubusercontent.com/16903052/103243593-5ea01100-4928-11eb-94e8-4dd9ba2b90a3.png)

**Comment by h2zero** [comment]
Thanks, I see the issue now, will update that branch when done.

**Comment by h2zero** [comment]
Just pushed a proper fix, sorry about that. I tested this against my NimBLE server device and it seems to be working correctly. Please try again if you don't mind and also try without `getServices(true)` as it should now work without.

**Comment by tonton81** [comment]
yup it works with and without getServices(true)

![image](https://user-images.githubusercontent.com/16903052/103245814-58f9f980-492f-11eb-9eee-471eae53cb6c.png)

**Comment by h2zero** [comment]
Awesome, thank you for your patience. I will merge it then.

@wakwak-koba I'm curious if this will fix your issue as well? Please post back here if you test it.

**Comment by tonton81** [comment]
Does NimBLE also work on Adafruit's nRF52 boards?

**Comment by h2zero** [comment]
The answer to this is yes and no lol. You could run the mynewt OS with NimBLE on it as it is supported I believe (should be). However I have not yet ported this library to support it (future project).

**Comment by tonton81** [comment]
Hey i think the disconnect() issues have been ressolved, i will have to let it run to see if it's good. I think the nullptr issue on writeValue during a failed characteristic match leaving isConnected() intact as true was the culprit

**Comment by h2zero** [comment]
Can you post a log of the disconnect issue? I'm working on finding a solution to this but it seems to change with circumstances.

**Comment by tonton81** [comment]
Hmm I will have to catch it again. All that happens is after consecutive disconnects, further disconnect()'s actually do nothing to the connection anymore

**Comment by h2zero** [comment]
If I'm interpreting this correctly you are doing something like:
```
while(isConnected()) {
    disconnect();
   delay():
}
```

If so, that may cause the issue as the controller will stop responding. Only need to call it once, delay until the callback or for the supervision timeout time (+a few ms).

**Comment by tonton81** [comment]
i usually disconnect() up to 4 clients (only 2 online) every 7 seconds (if theyre online)

![image](https://user-images.githubusercontent.com/16903052/103256048-bc008600-4959-11eb-8aa1-e3583ce73433.png)

**Comment by h2zero** [comment]
This actually reminds me of something I did years ago in the old library to work around this, completely forgot about it. What I did was set a flag, isDisconnecting, and tested against that and isConnected to decide if disconnect should be called. I'm still playing with this as well but I can only reproduce the situation occasionally on peripherals with poor connections.

**Comment by tonton81** [comment]
[dbgesp.txt](https://github.com/h2zero/NimBLE-Arduino/files/5749501/dbgesp.txt)

check this out:
D NimBLEScan: ">> stop()"
D NimBLEScan: "<< stop()"
D NimBLEClient: ">> disconnect()"
E NimBLEClient: "ble_gap_terminate failed: rc=2 "
D NimBLEClient: "<< disconnect()"

**Comment by h2zero** [comment]
Yep rc=2 means the NimBLE host stack thinks you're already disconnected. When you called it that time it was already in progress waiting for the controller to callback when it was complete.

**Comment by tonton81** [comment]
if thats the case, 2 means it's already dropped, I'll test this:

        if ( rc == 2 ) m_isConnected = false;
in the ::disconnect() function

**Comment by h2zero** [comment]
If you do that, the callback won't happen unless you comment out the 2 lines [here](https://github.com/h2zero/NimBLE-Arduino/blob/bc52eac5618c45bcfc00b1004bc25b3b1709f0ae/src/NimBLEClient.cpp#L703)

**Comment by tonton81** [comment]
Really?
 ok, how about:

![image](https://user-images.githubusercontent.com/16903052/103257426-2831b880-495f-11eb-8653-7f83250fadf2.png)

**Comment by h2zero** [comment]
Yeah, actually your original idea is worth trying with those lines commented out, I don't think there will be any issue without them. Those were a throwback to the original library and that check is not necessary now I believe.

**Comment by tonton81** [comment]
I found out where it is blocking after several disconnects leading to a standstill. It'll stop near line 218 of NimBLEClient.cpp
I change the timeout to 5 seconds so it can kick start the loop, but it's something in the ::connect() method that gets stuck after all the disconnects
`ulTaskNotifyTake(pdTRUE, /*portMAX_DELAY*/5000UL);`

**Comment by h2zero** [comment]
That would only become stuck if the controller stopped sending events or perhaps calling `connect()` on multiple clients at nearly the same time. We should move this discussion to a new issue as it's not related to the original.

**Comment by h2zero** [comment]
@tonton81 Please check my comment [here](https://github.com/h2zero/NimBLE-Arduino/issues/155#issuecomment-752265334)

**Comment by wakwak-koba** [comment]
> @wakwak-koba I'm curious if this will fix your issue as well? Please post back here if you test it.

I don't know if the conditions are exactly the same because I can't find the source code from half a year ago, but `pClient->getService((uint16_t)0x1812)` succeeded without calling `pClient->getServices(true)`

So I'm sure it's okay !!

**Comment by h2zero** [comment]
@wakwak-koba Thanks, sorry it took so long to realize what the problem was! All of my peripheral devices are custom nrf5 based and those convert the uuid to 128bit when 16bit is requested automatically.
