### ISSUE TITLE
Ondisconnect function not working when device disconnecting

### ISSUE THREAD

**Issue by kushalpatelkushal** [h2zero/NimBLE-Arduino#917]
Hi,

I am using NimBLE v1.4.2. when i am connecting to device, it connects to device and i get onconnect callback. when i disconnect, i got ondisconnect callback. Issue happens when device is sending data like 128 data in 1 second, when device disconnect, i dont get ondisconnect callback. I dont know what to do in this case? I also tried numconnected device function to find if device is connected or not.

**Comment by h2zero** [comment]
I believe this to be an issue with the controller, which requires a fix/update with the Arduino core and/or esp-idf.

**Comment by h2zero** [comment]
I just tested this with arduino core 3.0.1 and it works fine, this must be something in the new core versions.

**Comment by h2zero** [comment]
Appears to work fine win arduino core 3.1.3 as well.

**Comment by kushalpatelkushal** [comment]
i am using esp32 controller. any test code to test on this issue with esp32?

**Comment by h2zero** [comment]
@kushalpatelkushal Please test with the latest nimble core update that was just merged [8f32a23](https://github.com/h2zero/NimBLE-Arduino/commit/8f32a23e2c8a0071b98345915388eb0146b6bfdc)

**Comment by h2zero** [comment]
It's been reported that the issue has be resolved in the latest Arduino core. Please update that to version 3.2 and test.

**Comment by h2zero** [comment]
Closing as there has been no update, please reopen if it's still an issue.

**Comment by cl0rm** [comment]
on framework-arduinoespressif32 @ 3.20017.241212+sha.dcc1105b it seems to be still an issue
if i disconnect from android phone (nrf connect), disconnect event is not triggered ( also advertising does't restart)
if i disable bt on that phone instead, callback is triggered with reason 533.
